spring:
  application:
    name: event-service

server:
  port: ${PORT:8080}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

app:
  security:
    jwt:
      secret: "change-me-change-me-change-me-change-me-change-me"
      issuer: "event-service"
      expiration-minutes: 60

logging:
  level:
    root: INFO
    edu.jhu.eventservice: DEBUG
    org.springframework.security: INFO
